<a href="https://colab.research.google.com/github/robinkm0610/Tensorflow/blob/main/Tensorflow1_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Basics

Tensor is a multidimentional array that can run on GPU - A tensor is a N-dimensioanl array of data.

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.12.0


## Initialization of Tensors

In [6]:
x = tf.constant(4, shape = (1,1), dtype = tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [7]:
x = tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [10]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [18]:
x = tf.zeros((2,3))
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [19]:
x = tf.eye((3)) #### identity matrix
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [21]:
x = tf.random.normal((3,3), mean = 0, stddev = 1) ### standard normal distribution
print(x)

tf.Tensor(
[[-1.540437    1.6574621  -0.70560867]
 [-1.4513301  -1.6617024  -0.17443544]
 [ 0.8850249  -0.04232702  0.06660955]], shape=(3, 3), dtype=float32)


In [22]:
x  = tf.random.uniform((3,3), minval = 0, maxval = 1)
print(x)

tf.Tensor(
[[0.07303035 0.377818   0.911029  ]
 [0.54016376 0.4259944  0.76573896]
 [0.6075467  0.531862   0.7709966 ]], shape=(3, 3), dtype=float32)


In [23]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [24]:
x = tf.range(start = 1, limit = 10, delta = 2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [27]:
x = tf.cast( x, dtype = tf.float64) ### type casting - tf.float(16,32,64) tf.int(8,16,32,64) - tf.bool
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


## Mathematical Operations

In [30]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])
z = tf.add(x,y)
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [31]:
z = x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [33]:
z = tf.subtract(x,y)
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [34]:
z = x-y
print(z)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [36]:
z = tf.divide(x,y)
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [37]:
z = x/y
print(z)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [38]:
z  = tf.multiply(x,y)
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [39]:
z = x*y
print(z)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [40]:
z = tf.tensordot(x,y, axes = 1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [41]:
z = tf.reduce_sum(x * y, axis = 0)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [43]:
z = x ** 5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [45]:
x = tf.random.normal((2,3))
print(x)
y = tf.random.normal((3,4))
print(y)
z = tf.matmul(x,y) ### matrix multiplication
print(z)

tf.Tensor(
[[-0.17167345 -1.3147444  -0.45718607]
 [-0.5002254  -0.688566    0.5884912 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.5667822   0.1409023  -1.0023388   0.6839714 ]
 [-0.31465116 -0.8874738   1.0236971  -0.5213404 ]
 [ 0.6318374  -0.7190421  -1.2826223  -2.209361  ]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[ 0.02751711  1.471348   -0.5874281   1.5780988 ]
 [ 0.30497003  0.11745146 -0.9582997  -1.2833521 ]], shape=(2, 4), dtype=float32)


In [47]:
z = x @ y ### similar to matix multiplication
print(z)

tf.Tensor(
[[ 0.02751711  1.471348   -0.5874281   1.5780988 ]
 [ 0.30497003  0.11745146 -0.9582997  -1.2833521 ]], shape=(2, 4), dtype=float32)


## Indexing

In [49]:
x = tf.constant([0,1,2,3,4,5,6,7,8])
print(x[:]) ## print all elements

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [51]:
print(x[1:]) #print all other than 0 index

tf.Tensor([1 2 3 4 5 6 7 8], shape=(8,), dtype=int32)


In [52]:
print(x[1:3])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [53]:
print(x[::2])

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [55]:
print(x[::-1])

tf.Tensor([8 7 6 5 4 3 2 1 0], shape=(9,), dtype=int32)


In [57]:
indices = tf.constant([0,3])
x_ind = tf.gather(x,indices)
print(x_ind)

tf.Tensor([0 3], shape=(2,), dtype=int32)


In [58]:
x = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [59]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


## Reshaping

In [61]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [64]:
y = tf.reshape(x, (3,3))
print(y)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [66]:
z = tf.transpose(y, perm = [1,0])
print(z)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
